trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
  displayName: Download script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

- bash: |
    . build.sh --source-only
    init
    get_fab_version
    download_fab
    git_connect
    
    if ! git checkout $BRANCH_NAME; then
      git checkout -b $BRANCH_NAME
    fi
    
    repo="hello-rings"
    service="$repo-$BRANCH_NAME"
    echo "fab set --subcomponent $repo.$service buildId=$NUMBER"
    fab set --subcomponent $repo.$service buildId=$NUMBER
    echo "git status"
    git status
    git pull
    git add -A
    git config --global user.email "you@example.com"
    git config --global user.name "Azure DevOps Bot"
    git commit -m "Fab setting buildId"
    echo "git status"
    git status
    git push https://$ACCESS_TOKEN_SECRET@github.com/bnookala/hello-rings-cluster
  displayName: Fab set version
  env:
    BRANCH_NAME: $(Build.SourceBranchName)
    REPO: "https://github.com/bnookala/hello-rings-cluster"
    NUMBER: $(Build.BuildId)